// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yauqjjwpsbxnkaszzfoh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlhdXFqandwc2J4bmthc3p6Zm9oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MzE1MjIsImV4cCI6MjA3MTIwNzUyMn0.M4tBmH9oTxSM7bfHhisR5Z_wBwALS6S3GECONgGMUGo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});